// DTO 子命名空间全局导入
global using PlatformBase.Application.Dtos.CommonModule;
global using PlatformBase.Application.Dtos.AuthModule;
global using PlatformBase.Application.Dtos.UserModule;
global using PlatformBase.Application.Dtos.RoleModule;
global using PlatformBase.Application.Dtos.PermissionModule;
global using PlatformBase.Application.Dtos.SystemParamModule;
global using PlatformBase.Application.Dtos.DataDictModule;
global using PlatformBase.Application.Dtos.OperationLogModule;
global using PlatformBase.Application.Dtos.MenuModule;
global using PlatformBase.Application.Dtos.FileModule;
global using PlatformBase.Application.Dtos.NotificationModule;

// Service 子命名空间全局导入
global using PlatformBase.Application.Services.AuthModule;
global using PlatformBase.Application.Services.UserModule;
global using PlatformBase.Application.Services.RoleModule;
global using PlatformBase.Application.Services.PermissionModule;
global using PlatformBase.Application.Services.SystemParamModule;
global using PlatformBase.Application.Services.DataDictModule;
global using PlatformBase.Application.Services.MenuModule;
global using PlatformBase.Application.Services.FileModule;
global using PlatformBase.Application.Services.NotificationModule;
global using PlatformBase.Application.Services.OperationLogModule;
global using PlatformBase.Application.Services.JobModule;
global using PlatformBase.Application.Services.TenantModule;
global using PlatformBase.Application.Services.OrganizationModule;
global using PlatformBase.Application.Services.ImportExportModule;
